[tool.black]
line-length = 120
target-version = ['py311']

[tool.isort]
profile = "black"
line_length = 120

[tool.flake8]
max-line-length = 120

[tool.bandit.assert_used]
skips = ["tests/*"]

[[tool.mypy.overrides]]
module = "benedict.*"
ignore_missing_imports = true
